# Generated by Django 4.0.3 on 2024-06-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marksheetdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enrollment', models.CharField(max_length=20)),
                ('year', models.CharField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2024, max_length=5)),
                ('department', models.CharField(choices=[('Artificial Intelligence Department', 'Artificial Intelligence Department'), ('Information Technology Department', 'Information Technology Department'), ('Computer Engineering Department', 'Computer Engineering Department'), ('Mechanical Department', 'Mechanical Department'), ('Electrical Department', 'Electrical Department'), ('Civil Department', 'Civil Department')], max_length=200)),
                ('result', models.TextField()),
                ('total_marks', models.PositiveBigIntegerField()),
                ('total_marks_obtained', models.PositiveBigIntegerField()),
            ],
        ),
    ]
