# Generated by Django 4.0.3 on 2024-06-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allstaffdatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=1000, null=True, upload_to='uploads/')),
                ('name', models.CharField(max_length=2000)),
                ('designation', models.CharField(default=None, max_length=2000)),
                ('department', models.CharField(choices=[('Principal', 'Principal'), ('Artificial Intelligence Department', 'Artificial Intelligence Department'), ('Information Technology Department', 'Information Technology Department'), ('Computer Engineering Department', 'Computer Engineering Department'), ('Mechanical Department', 'Mechanical Department'), ('Electrical Department', 'Electrical Department'), ('Civil Department', 'Civil Department')], default=None, max_length=200, null=True)),
            ],
        ),
    ]
