# Generated by Django 4.0.3 on 2024-06-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstaffdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstaffdatabase',
            name='aadhar_no',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='allstaffdatabase',
            name='addressline',
            field=models.TextField(default=None, max_length=2000),
        ),
    ]
