# Generated by Django 4.0.3 on 2024-06-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstaffdatabase', '0002_allstaffdatabase_aadhar_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstaffdatabase',
            name='contact',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
