# Generated by Django 4.0.3 on 2024-06-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allstaffdatabase', '0005_remove_allstaffdatabase_selfcontact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allstaffdatabase',
            name='selfc',
        ),
    ]
