# Generated by Django 4.0.3 on 2024-06-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstaffdatabase', '0007_remove_allstaffdatabase_addressline'),
    ]

    operations = [
        migrations.AddField(
            model_name='allstaffdatabase',
            name='Self Contact',
            field=models.CharField(default=None, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='allstaffdatabase',
            name='addressline',
            field=models.TextField(default=None, max_length=2000),
        ),
    ]
