# Generated by Django 4.0.3 on 2024-06-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allstaffdatabase', '0008_allstaffdatabase_self contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allstaffdatabase',
            old_name='Self Contact',
            new_name='contact',
        ),
    ]
