# Generated by Django 4.0.3 on 2024-06-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstaffdatabase', '0010_alter_allstaffdatabase_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstaffdatabase',
            name='contact',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
