# Generated by Django 4.0.3 on 2024-06-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, max_length=250, upload_to='uploads/')),
                ('name', models.CharField(max_length=200)),
                ('review', models.TextField(default=None, max_length=2000)),
            ],
        ),
    ]
