# Generated by Django 4.0.3 on 2024-06-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=5, max_length=1),
        ),
    ]
