# Generated by Django 4.0.3 on 2024-06-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(default=None, max_length=250, null=True, upload_to='uploads/')),
                ('detail', models.TextField(max_length=10000)),
            ],
        ),
    ]
