# Generated by Django 4.0.3 on 2024-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studymaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=500)),
                ('file', models.FileField(max_length=1000, null=True, upload_to='uploads/')),
                ('filename', models.TextField(max_length=500)),
            ],
        ),
    ]
