# Generated by Django 4.0.3 on 2024-06-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studymaterial', '0002_alter_studymaterial_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='department',
            field=models.CharField(choices=[('Artificial Intelligence Department', 'Artificial Intelligence Department'), ('Information Technology Department', 'Information Technology Department'), ('Computer Engineering Department', 'Computer Engineering Department'), ('Mechanical Department', 'Mechanical Department'), ('Electrical Department', 'Electrical Department'), ('Civil Department', 'Civil Department')], max_length=200),
        ),
    ]
