# Generated by Django 4.0.3 on 2024-06-07 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allannouncements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('General', 'General'), ('Event', 'Event'), ('Update', 'Update'), ('Alert', 'Alert')], default='General', max_length=50)),
                ('announcement', models.TextField(max_length=3000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
