# Generated by Django 4.0.3 on 2024-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstudentdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstudentdata',
            name='department',
            field=models.CharField(choices=[('Artificial Intelligence Department', 'Artificial Intelligence Department'), ('Information Technology Department', 'Information Technology Department'), ('Computer Engineering Department', 'Computer Engineering Department'), ('Mechanical Department', 'Mechanical Department'), ('Electrical Department', 'Electrical Department'), ('Civil Department', 'Civil Department')], default=None, max_length=500, null=True),
        ),
    ]
