# Generated by Django 4.0.3 on 2024-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstudentdata', '0002_alter_allstudentdata_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstudentdata',
            name='department',
            field=models.CharField(choices=[('Artificial Intelligence Department', 'Artificial Intelligence Department'), ('Information Technology Department', 'Information Technology Department'), ('Computer Engineering Department', 'Computer Engineering Department'), ('Mechanical Engineering Department', 'Mechanical Engineering Department'), ('Electrical Engineering Department', 'Electrical Engineering Department'), ('Civil Engineering Department', 'Civil Engineering Department')], default=None, max_length=500, null=True),
        ),
    ]
