# Generated by Django 4.0.3 on 2024-06-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='file',
        ),
        migrations.AddField(
            model_name='slideshow',
            name='name',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
