# Generated by Django 4.0.3 on 2024-06-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slideshow', '0002_remove_slideshow_file_slideshow_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='name',
        ),
        migrations.AddField(
            model_name='slideshow',
            name='file',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to=''),
        ),
    ]
